FROM apache/airflow:2.7.1-python3.11

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    psycopg2-binary \
    pyyaml \
    jsonschema \
    dbt-core \
    dbt-postgres
