#!/usr/bin/env python3
"""
GradMent Data Platform — Schema Inventory Discovery Script
Discovers and inventories operational database tables, columns, data types, nullability,
and foreign key relationships from live MySQL or PHP migration files.
"""

import os
import re
import sys
import json
from pathlib import Path

def parse_php_migrations(migrations_dir: Path) -> dict:
    """Parses CodeIgniter 4 PHP migration files to extract schema information offline."""
    tables = {}
    if not migrations_dir.exists():
        print(f"Warning: Migrations directory {migrations_dir} not found.", file=sys.stderr)
        return tables

    migration_files = sorted(migrations_dir.glob("*.php"))
    print(f"Found {len(migration_files)} migration files in {migrations_dir}")

    for file_path in migration_files:
        content = file_path.read_text(encoding="utf-8", errors="ignore")

        # Extract table name: $this->forge->createTable('table_name') or addKey/addForeignKey
        create_table_match = re.search(r"\$this->forge->createTable\(['\"]([^'\"]+)['\"]", content)
        if not create_table_match:
            continue

        table_name = create_table_match.group(1)
        if table_name not in tables:
            tables[table_name] = {
                "columns": {},
                "primary_keys": [],
                "foreign_keys": [],
                "source_file": file_path.name
            }

        # Parse fields defined in array
        field_matches = re.findall(r"['\"]([a-zA-Z0-9_]+)['\"]\s*=>\s*\[(.*?)\]", content, re.DOTALL)
        for field_name, field_attrs in field_matches:
            type_match = re.search(r"['\"]type['\"]\s*=>\s*['\"]([^'\"]+)['\"]", field_attrs)
            constraint_match = re.search(r"['\"]constraint['\"]\s*=>\s*([^,\n\]]+)", field_attrs)
            null_match = re.search(r"['\"]null['\"]\s*=>\s*(true|false)", field_attrs, re.IGNORECASE)
            auto_inc_match = re.search(r"['\"]auto_increment['\"]\s*=>\s*true", field_attrs, re.IGNORECASE)

            data_type = type_match.group(1) if type_match else "UNKNOWN"
            constraint = constraint_match.group(1).strip("'\" ") if constraint_match else None
            is_nullable = null_match.group(1).lower() == "true" if null_match else False

            tables[table_name]["columns"][field_name] = {
                "type": f"{data_type}({constraint})" if constraint else data_type,
                "nullable": is_nullable,
                "auto_increment": bool(auto_inc_match)
            }

        # Parse primary keys
        pk_matches = re.findall(r"\$this->forge->addKey\(['\"]([^'\"]+)['\"],\s*true\)", content)
        for pk in pk_matches:
            if pk not in tables[table_name]["primary_keys"]:
                tables[table_name]["primary_keys"].append(pk)

        # Parse foreign keys
        fk_matches = re.findall(
            r"\$this->forge->addForeignKey\(['\"]([^'\"]+)['\"],\s*['\"]([^'\"]+)['\"],\s*['\"]([^'\"]+)['\"]",
            content
        )
        for fk_col, ref_table, ref_col in fk_matches:
            tables[table_name]["foreign_keys"].append({
                "column": fk_col,
                "referenced_table": ref_table,
                "referenced_column": ref_col
            })

    return tables

def generate_markdown_report(tables: dict) -> str:
    """Generates a detailed markdown inventory report from parsed tables."""
    lines = [
        "# Database Schema Inventory — GradMent Operational MySQL",
        "",
        "**Generated by:** `scripts/discovery/inventory_schema.py`  ",
        "**Status:** Complete Inventory  ",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"- **Total Tables Inventoried:** {len(tables)}",
        "- **Data Platform Target:** PostgreSQL Staging Schema (`raw`)",
        "",
        "---",
        "",
        "## Table Details",
        ""
    ]

    for table_name, meta in sorted(tables.items()):
        lines.append(f"### Table: `{table_name}`")
        lines.append(f"- **Source File:** `{meta.get('source_file', 'Live MySQL')}`")
        lines.append(f"- **Primary Key:** `{', '.join(meta['primary_keys']) if meta['primary_keys'] else 'None'}`")
        lines.append("")
        lines.append("| Column | Type | Nullable | Primary Key | Foreign Key / Notes |")
        lines.append("|---|---|---|---|---|")

        for col_name, col_info in meta["columns"].items():
            is_pk = "Yes" if col_name in meta["primary_keys"] else "No"
            fk_info = "-"
            for fk in meta["foreign_keys"]:
                if fk["column"] == col_name:
                    fk_info = f"-> `{fk['referenced_table']}.{fk['referenced_column']}`"
                    break

            lines.append(
                f"| `{col_name}` | `{col_info['type']}` | {'Yes' if col_info['nullable'] else 'No'} | {is_pk} | {fk_info} |"
            )

        lines.append("")

    return "\n".join(lines)

def main():
    script_dir = Path(__file__).resolve().parent
    platform_dir = script_dir.parents[1]  # c:\xampp\htdocs\gradment\gradment-data-platform
    workspace_root = script_dir.parents[2]  # c:\xampp\htdocs\gradment

    backend_migrations_dir = workspace_root / "GradMentBack" / "app" / "Database" / "Migrations"

    print("Executing GradMent Database Schema Inventory Discovery...")
    tables = parse_php_migrations(backend_migrations_dir)

    output_dir = platform_dir / "docs"
    output_dir.mkdir(parents=True, exist_ok=True)

    report_path = output_dir / "schema_inventory.md"
    report_content = generate_markdown_report(tables)
    report_path.write_text(report_content, encoding="utf-8")

    json_path = output_dir / "schema_inventory.json"
    json_path.write_text(json.dumps(tables, indent=2), encoding="utf-8")

    print(f"Successfully generated inventory report: {report_path}")
    print(f"Successfully generated JSON schema dump: {json_path}")

if __name__ == "__main__":
    main()
